name: app
description: App 
publish_to: 'none' 

version: 3.0.1+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  match: ^0.4.1
  sqflite: ^2.3.0
  dio: ^5.3.2
  intl: 0.19.0
  synchronized: ^3.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  connectivity_plus: ^6.1.1
  loading_animation_widget: ^1.3.0
  top_snackbar_flutter: ^3.1.0
  validatorless: ^1.2.3
  date_picker_timeline: ^1.2.5
  flutter_dotenv: ^5.1.0  
  shared_preferences: ^2.2.0
  logger: ^2.0.1
  package_info_plus: ^8.1.2
  cupertino_icons: ^1.0.5
  uuid: ^4.1.0
  url_launcher: ^6.1.12
  auto_size_text: ^3.0.0
  jwt_decoder: ^2.0.1
  share_plus: ^10.1.3
  flutter_svg: ^2.0.16
  awesome_snackbar_content: ^0.1.4
  freezed_annotation: ^2.0.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  syncfusion_flutter_charts: ^28.1.36
  flutter_form_builder: ^9.6.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  match_generator: ^0.4.2
  flutter_native_splash: ^2.3.2
  icons_launcher: ^3.0.0
  json_serializable: ^6.0.0
  freezed: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: mplus1
      fonts:
        - asset: assets/fonts/mplus1/MPLUS1p-Light.ttf
          weight: 300
        - asset: assets/fonts/mplus1/MPLUS1p-Regular.ttf
          style: normal
        - asset: assets/fonts/mplus1/MPLUS1p-Medium.ttf
          weight: 500
        - asset: assets/fonts/mplus1/MPLUS1p-Bold.ttf
          weight: 700
        - asset: assets/fonts/mplus1/MPLUS1p-ExtraBold.ttf
          weight: 800  
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf


